Repository tacosontitan/Glitter, pull requests merged in 2023-01, with the labels that each got.

#37 Implement `IHostedService` in `EncapsulatedEventHandler`.
  src/Glitter.Discord/Events/ConnectedEventHandler.cs
  src/Glitter.Discord/Events/DisconnectedEventHandler.cs
  src/Glitter.Discord/Events/LogEventHandler.cs
  src/Glitter.Discord/Events/LoggedInEventHandler.cs
  src/Glitter.Discord/Events/LoggedOutEventHandler.cs
  src/Glitter.Discord/Events/MessageReceivedEventHandler.cs
  src/Glitter/EncapsulatedEventHandler.cs
Labels: refactor

#46 Scaffolding
  .config/dotnet-tools.json
  .github/workflows/dotnet.yml
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/tasks.json
  Glitter.sln
  nuget.config
  samples/Freya/Freya.csproj
  samples/Freya/Logging/ColoredConsoleLogger.cs
  samples/Freya/Logging/ColoredConsoleLoggerProvider.cs
  samples/Freya/Logging/ColoredConsoleLoggerServiceExtensions.cs
  samples/Freya/Program.cs
  samples/Freya/appsettings.json
  src/Glitter.Commands.OpenSource/Glitter.Commands.OpenSource.csproj
  src/Glitter.Discord/Commands/SlashCommandRegistrationRequestHandler.cs
  src/Glitter.Discord/DiscordChatbot.cs
  src/Glitter.Discord/Events/LogEventHandler.cs
  src/Glitter.Discord/Glitter.Discord.csproj
  src/Glitter/Commands/Command.cs
  src/Glitter/Commands/CommandRequestHandler.cs
  src/Glitter/Glitter.csproj
  test/Glitter.Tests/Glitter.Tests.csproj
  test/Glitter.Tests/RequestParserTests.cs
  test/Glitter.Tests/Usings.cs
Labels: enhancement, repository, refactor

#56 Changed UseGlitter extension to AddGlitter
  README.md
  samples/Freya/Program.cs
  src/Glitter/GlittertExtensions.cs
Labels: refactor

#57 Update the `cleanup` branch.
  README.md
  samples/Freya/Program.cs
  src/Glitter/GlittertExtensions.cs
Labels: repository

#84 Changed the visibility of SlashCommand constructor to 'protected'
  src/Glitter/Ai/Chatbot.cs
  src/Glitter/Ai/ChatbotWithSettings.cs
  src/Glitter/Commands/Command.cs
  src/Glitter/Commands/SlashCommand.cs
Labels: refactor

#85 Remove unused _id field from Command
  src/Glitter/Commands/Command.cs
Labels: refactor

#91 Removed using
  .github/workflows/codesee-arch-diagram.yml
  src/Glitter.Commands.OpenSource/Baseline/HelpCommand.cs
Labels: refactor
